### ISSUE TITLE
table_view_builder

### ISSUE THREAD

**Issue by tmnyoni** [alecmus/lecui#5]
the table_view_builder takes some time to render data after pushing a row into the table using the push_back function.

like so:

widgets::table_view_builder::specs(*this, main_page_name_ + "/main_tab/coupons/coupons_table")
	.data().push_back({ { "#", "7"}, {"Date", "10-June-20"}, {"Issued to", "new"}, {"Serial Number", "added-for-testing"}});

And if you using values that are determined on runtime, the table sometimes doesn't render the data.

**Comment by alecmus** [comment]
According to the documentation, after making changes to UI elements you need to call the .update() method of the form class for the changes to be reflected as soon as possible, otherwise they will only come into effect the next time you move your mouse over the form or the next time a timer is called etc. Therefore, call the update() method explicitly.
