### ISSUE TITLE
Failing to change the background color of a label

### ISSUE THREAD

**Issue by tmnyoni** [alecmus/lecui#6]
I seem to be failing to change the colour of the label. I wonder if I am doing it wrong or there is a bug.

This is my code:

```C++
widgets::label_builder fuel_caption(coupon_details_pane.get());
	fuel_caption()
		.text("Fuel")
		.color_text(caption_color_)
		.color_fill().green();
```

I also tried:
```C++
.color_fill({0, 0, 0, 100});
```

And:
```C++
.color_fill().get_green();
```

**Comment by alecmus** [comment]
Labels, <strong>by design</strong>, do not have a background. This is partly because the actual rectangular area used by a label is determined not by the co-ordinates specified through the .rect property, but by the actual contents of the label (the .rect property just defines the maximum area that the label is allowed to occupy). As such, if you need to add a background to a label you need to use the rectangle widget. Just add a rectangle and add a label on top of it (using same .rect coordinates).

To see that the .color_fill property is not used at all by the label check the implementation file [here](https://github.com/alecmus/lecui/blob/master/widgets/label/label_impl.cpp).
